### ISSUE TITLE
Can't activate Addon in Blender 2.76 / Debian

### ISSUE THREAD

**Issue by gree303** [ApoorvaJ/BlenderSFM#2]
I'm not able to activate the addon. Is there any workaround or fix to it?
"ImportError: No module named 'blenderSFM'"

**Comment by ApoorvaJ** [comment]
This was a college project. I'm not actively supporting it at the moment. Sorry about that. Seems like a fairly basic Python error, though.

**Comment by gree303** [comment]
After inspecting the files I suspect it's only compatible with windows? As of now I'm running Linux/Debian. Maybe it's related to the wrong/missleading "Path" in PointCloud.py

So; can I run it with Blender/Linux but have to remap all *.exe to be supported through wine?
Based on your knowledge about this project, do you think this is doable?

I understand you are not working anymore on this. Maybe you find time answering the one or other question related to it. Thanks.

**Comment by ApoorvaJ** [comment]
Yup. This is Windows only. No clue whether it'll run with Wine. This project just streamlined the workflow across multiple binaries that did feature extraction and point cloud generation. You can figure out what the python script does, acquire Linux binaries (provided they exist), and run it manually.
